---
- name: Converge
  hosts: all
  tasks:
    - name: "Include coaxial.nzbget"
      ansible.builtin.include_role:
        name: "coaxial.nzbget"

    - name: Install curl (for tests)
      ansible.builtin.package:
        name: curl
        state: present
